--- # Metadata
- id: RuntimeEnvironment
- description: This rule assesses whether an [Resource] that has the property [p1:runtimeLanguage] set respectively, also has the property [p2:runtimeVersion] correctly configured.
- version: 1.0 
- comments: This check ensures that the runtime language and version are properly set, mitigating potential security risks and ensuring application reliability.
--- # Configuration data
- p:
  - operator: ">="
  - targetValue: 
      - p1:runtimeLanguage: "Java"
        p2:runtimeVersion: 21
      - p1:runtimeLanguage: "Python"
        p2:runtimeVersion: 3.12
      - p1:runtimeLanguage: "PHP"
        p2:runtimeVersion: 21