name: Migrate EMERALD Metric
description: Create issue for migrating a metric from EMERALD to this repository
title: 'Migrate EMERALD metric ""'
labels:
  - migration
  - emerald
body:
  - type: dropdown
    id: browsers
    attributes:
      label: Which project? 
      multiple: true
      options:
        - EMERALD
        - COBALT
