name: Migrate EMERALD Metric
description: Create issue for migrating a metric from EMERALD to this repository
title: 'Migrate EMERALD metric ""'
labels:
  - migration
  - emerald
body:
  - type: markdown
    attributes:
      value: |
        Migrate the above metric to this repository
