name: Migrate EMERALD Metric
description: Migrate metric "${{ metric }}" from EMERALD to the cluster
title: 'Migrate EMERALD metric "${{ metric }}"'
labels:
  - migration
  - emerald
body:
  - type: input
    id: metric
    attributes:
      label: Metric name
      description: Enter the EMERALD metric to migrate
