# Metadata
id: 26F206B2-EF01-4183-A431-F17ED951A75E
name: PolicyTopicIncluded
description: This rule assesses whether any [Resource] has the [Policy][p1:topic] within the defined set of required topics.
implementationGuidelines:
  AMOE: "Which topics are comprised by the defined asset management policy?"
version: v1 
comments: Valid topics for this rule are inventory, ownership, decommissioning, and none. Policies missing these may lead to gaps in asset tracking and accountability.

--- 
# Configuration data
configuration:
  p1:
    operator: "isIn"
    targetValue: ["inventory", "ownership", "decommissioning", "none"]