name: Merge Ontology and generate proto file

on: [pull_request]
permissions:
  contents: write
  pull-requests: write

jobs:
    ontology:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            ref: ${{ github.head_ref }}
        - name: Set up Git user
          run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
        - name: Switch to branch
          run: |
            git checkout ${{ github.head_ref }}
        - name: Download ROBOT
          run: |
            wget https://github.com/ontodev/robot/releases/download/v1.9.5/robot.jar
        # Delete core/evidence.owx from catalog file. We do not need the evidence object in the merged ontology, that would lead to an error in the proto file generation.
        - name: Delete evidence.owx from catalog file
          run: |
            sed -i '/uri="core\/evidence\.owx"/d' ontology/1.0/catalog-v001.xml
        - name: Delete evidence.owx from core file
          run: |
             sed -i '/<Import>https:\/\/ontology.cybersecuritycertcluster.eu\/core\/evidence<\/Import>/d' ontology/1.0/core.owx
        - name: Merge owx files
          uses: docker://openjdk:11
          with:
            args: java -jar robot.jar -vvv merge 
              --catalog ontology/1.0/catalog-v001.xml
              --input ontology/1.0/ontology.owx 
              --output ontology/1.0/ontology-merged.owx
        - name: Generate proto file for ontology
          run: |
            go install github.com/oxisto/owl2proto/cmd/owl2proto@latest
            $HOME/go/bin/owl2proto generate-proto \
            --root-resource-name=/classes/Resource ontology/1.0/ontology-merged.owx \
            --header-file=ontology/csc_hub_header.proto \
            --output-path=ontology/1.0/ontology.proto \
            --full-semantic-mode=false \
            --deterministic-field-numbers=true
        - name: Upload Artifact ontology-merged.owx 
          uses: actions/upload-artifact@v4
          with:
            name: ontology-merged
            path: ontology/1.0/merged/ontology-merged.owx 
        - name: Commit merged OWX file
          run: |
              git add ontology/1.0/ontology-merged.owx 
              git commit -m "Add merged ontology file [skip ci]" || echo "No changes to commit"
              git push
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Commit ontology.proto file
          run: |
              git add ontology/1.0/ontology.proto
              git commit -m "Add generated proto file [skip ci]" || echo "No changes to commit"
              git push
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        